from __future__ import annotations

UNIVERSE: dict[str, dict[str, str]] = {
    "Stock": {
        "AAPL": "Apple",
        "MSFT": "Microsoft",
        "GOOGL": "Alphabet (Class A)",
        "AMZN": "Amazon",
        "NVDA": "NVIDIA",
        "META": "Meta Platforms",
        "TSLA": "Tesla",
        "BRK-B": "Berkshire Hathaway (Class B)",
        "JPM": "JPMorgan Chase",
        "V": "Visa",
        "MA": "Mastercard",
        "WMT": "Walmart",
        "JNJ": "Johnson & Johnson",
        "UNH": "UnitedHealth",
        "PG": "Procter & Gamble",
        "HD": "Home Depot",
        "XOM": "ExxonMobil",
        "CVX": "Chevron",
        "BAC": "Bank of America",
        "KO": "Coca-Cola",
        "PEP": "PepsiCo",
        "DIS": "Disney",
        "NFLX": "Netflix",
        "ADBE": "Adobe",
        "CRM": "Salesforce",
        "ORCL": "Oracle",
        "AMD": "AMD",
        "INTC": "Intel",
        "CSCO": "Cisco",
        "IBM": "IBM",
        "PFE": "Pfizer",
        "MRK": "Merck",
        "LLY": "Eli Lilly",
        "COST": "Costco",
        "MCD": "McDonald's",
        "NKE": "Nike",
        "SBUX": "Starbucks",
    },
    "Commodity": {
        "GC=F": "Gold",
        "SI=F": "Silver",
        "PL=F": "Platinum",
        "PA=F": "Palladium",
        "HG=F": "Copper",
        "CL=F": "Crude Oil (WTI)",
        "BZ=F": "Brent Crude",
        "NG=F": "Natural Gas",
        "HO=F": "Heating Oil",
        "RB=F": "RBOB Gasoline",
        "ZC=F": "Corn",
        "ZW=F": "Wheat",
        "ZS=F": "Soybeans",
        "KC=F": "Coffee",
        "SB=F": "Sugar",
        "CC=F": "Cocoa",
        "CT=F": "Cotton",
        "LE=F": "Live Cattle",
        "HE=F": "Lean Hogs",
    },
    "Index": {
        "^GSPC": "S&P 500",
        "^DJI": "Dow Jones Industrial Average",
        "^IXIC": "Nasdaq Composite",
        "^NDX": "Nasdaq 100",
        "^RUT": "Russell 2000",
        "^VIX": "CBOE Volatility Index",
        "^FTSE": "FTSE 100 (UK)",
        "^GDAXI": "DAX (Germany)",
        "^FCHI": "CAC 40 (France)",
        "^STOXX50E": "Euro Stoxx 50",
        "^N225": "Nikkei 225 (Japan)",
        "^HSI": "Hang Seng (Hong Kong)",
        "^BSESN": "BSE Sensex (India)",
        "^AXJO": "ASX 200 (Australia)",
        "^BVSP": "Bovespa (Brazil)",
    },
    "Crypto": {
        "BTC-USD": "Bitcoin",
        "ETH-USD": "Ethereum",
        "SOL-USD": "Solana",
        "XRP-USD": "XRP",
        "ADA-USD": "Cardano",
        "DOGE-USD": "Dogecoin",
        "AVAX-USD": "Avalanche",
        "DOT-USD": "Polkadot",
        "LINK-USD": "Chainlink",
        "MATIC-USD": "Polygon",
        "LTC-USD": "Litecoin",
        "BCH-USD": "Bitcoin Cash",
        "UNI-USD": "Uniswap",
        "ATOM-USD": "Cosmos",
        "XLM-USD": "Stellar",
        "ETC-USD": "Ethereum Classic",
    },
    "ETF": {
        # ─── US Broad Market ───
        "SPY": "SPDR S&P 500",
        "IVV": "iShares Core S&P 500",
        "VOO": "Vanguard S&P 500",
        "SPLG": "SPDR Portfolio S&P 500",
        "VTI": "Vanguard Total Stock Market",
        "ITOT": "iShares Core S&P Total US",
        "SCHB": "Schwab US Broad Market",
        "QQQ": "Invesco Nasdaq 100",
        "QQQM": "Invesco Nasdaq 100 (lower-fee)",
        "DIA": "SPDR Dow Jones Industrial Average",
        "IWV": "iShares Russell 3000",
        # ─── US Size / Style ───
        "VUG": "Vanguard Growth",
        "IWF": "iShares Russell 1000 Growth",
        "SCHG": "Schwab Large-Cap Growth",
        "VTV": "Vanguard Value",
        "IWD": "iShares Russell 1000 Value",
        "SCHV": "Schwab Large-Cap Value",
        "IJH": "iShares Core S&P Mid-Cap",
        "VO": "Vanguard Mid-Cap",
        "IWR": "iShares Russell Mid-Cap",
        "IWM": "iShares Russell 2000",
        "IJR": "iShares Core S&P Small-Cap",
        "VB": "Vanguard Small-Cap",
        "SCHA": "Schwab US Small-Cap",
        "MGK": "Vanguard Mega Cap Growth",
        # ─── US Sectors ───
        "XLK": "Technology Select Sector",
        "XLF": "Financial Select Sector",
        "XLE": "Energy Select Sector",
        "XLV": "Health Care Select Sector",
        "XLY": "Consumer Discretionary Select Sector",
        "XLP": "Consumer Staples Select Sector",
        "XLI": "Industrial Select Sector",
        "XLU": "Utilities Select Sector",
        "XLB": "Materials Select Sector",
        "XLRE": "Real Estate Select Sector",
        "XLC": "Communication Services Select Sector",
        "SOXX": "iShares Semiconductor",
        "SMH": "VanEck Semiconductor",
        "IBB": "iShares Biotechnology",
        "XBI": "SPDR S&P Biotech",
        "KRE": "SPDR S&P Regional Banking",
        "KBE": "SPDR S&P Bank",
        "ITA": "iShares US Aerospace & Defense",
        "XOP": "SPDR S&P Oil & Gas E&P",
        "GDX": "VanEck Gold Miners",
        "GDXJ": "VanEck Junior Gold Miners",
        "XHB": "SPDR S&P Homebuilders",
        "HACK": "ETFMG Prime Cyber Security",
        "CIBR": "First Trust Nasdaq Cybersecurity",
        # ─── US Factors ───
        "MTUM": "iShares MSCI USA Momentum",
        "QUAL": "iShares MSCI USA Quality",
        "VLUE": "iShares MSCI USA Value",
        "USMV": "iShares MSCI USA Min Vol",
        "SPLV": "Invesco S&P 500 Low Volatility",
        "COWZ": "Pacer US Cash Cows 100",
        "MOAT": "VanEck Morningstar Wide Moat",
        # ─── US Dividend ───
        "SCHD": "Schwab US Dividend Equity",
        "VYM": "Vanguard High Dividend Yield",
        "VIG": "Vanguard Dividend Appreciation",
        "DGRO": "iShares Core Dividend Growth",
        "NOBL": "ProShares S&P 500 Dividend Aristocrats",
        "DVY": "iShares Select Dividend",
        # ─── International Developed ───
        "VEA": "Vanguard FTSE Developed Markets",
        "IEFA": "iShares Core MSCI EAFE",
        "SCHF": "Schwab International Equity",
        "VXUS": "Vanguard Total International Stock",
        "IXUS": "iShares Core MSCI Total International",
        "EFA": "iShares MSCI EAFE",
        "EWJ": "iShares MSCI Japan",
        "EWG": "iShares MSCI Germany",
        "EWU": "iShares MSCI UK",
        "EWC": "iShares MSCI Canada",
        # ─── Emerging Markets ───
        "VWO": "Vanguard FTSE Emerging Markets",
        "IEMG": "iShares Core MSCI Emerging Markets",
        "SCHE": "Schwab Emerging Markets Equity",
        "EEM": "iShares MSCI Emerging Markets",
        "FXI": "iShares China Large-Cap",
        "MCHI": "iShares MSCI China",
        "KWEB": "KraneShares CSI China Internet",
        "INDA": "iShares MSCI India",
        "EWZ": "iShares MSCI Brazil",
        "EWT": "iShares MSCI Taiwan",
        # ─── Bonds ───
        "AGG": "iShares Core US Aggregate Bond",
        "BND": "Vanguard Total Bond Market",
        "SCHZ": "Schwab US Aggregate Bond",
        "BNDW": "Vanguard Total World Bond",
        "TLT": "iShares 20+ Year Treasury",
        "IEF": "iShares 7-10 Year Treasury",
        "IEI": "iShares 3-7 Year Treasury",
        "SHY": "iShares 1-3 Year Treasury",
        "SGOV": "iShares 0-3 Month Treasury",
        "BIL": "SPDR Bloomberg 1-3 Month T-Bill",
        "LQD": "iShares iBoxx $ Investment Grade Corp",
        "VCIT": "Vanguard Intermediate-Term Corp Bond",
        "HYG": "iShares iBoxx High Yield Corp",
        "JNK": "SPDR Bloomberg High Yield Bond",
        "TIP": "iShares TIPS Bond",
        "VTIP": "Vanguard Short-Term TIPS",
        "MUB": "iShares National Muni Bond",
        "VTEB": "Vanguard Tax-Exempt Bond",
        "EMB": "iShares J.P. Morgan USD Emerging Markets Bond",
        "BSV": "Vanguard Short-Term Bond",
        "BIV": "Vanguard Intermediate-Term Bond",
        "BLV": "Vanguard Long-Term Bond",
        # ─── Commodities ───
        "GLD": "SPDR Gold Shares",
        "IAU": "iShares Gold Trust",
        "GLDM": "SPDR Gold MiniShares",
        "SLV": "iShares Silver Trust",
        "USO": "United States Oil Fund",
        "UNG": "United States Natural Gas Fund",
        "DBC": "Invesco DB Commodity Index",
        "PDBC": "Invesco Optimum Yield Diversified Commodity",
        "URA": "Global X Uranium",
        # ─── Real Estate ───
        "VNQ": "Vanguard Real Estate",
        "IYR": "iShares US Real Estate",
        "SCHH": "Schwab US REIT",
        "VNQI": "Vanguard Global ex-US Real Estate",
        # ─── Thematic / Innovation ───
        "ARKK": "ARK Innovation",
        "ARKG": "ARK Genomic Revolution",
        "ARKQ": "ARK Autonomous Tech & Robotics",
        "ARKW": "ARK Next Generation Internet",
        "ICLN": "iShares Global Clean Energy",
        "TAN": "Invesco Solar",
        "LIT": "Global X Lithium & Battery Tech",
        "ROBO": "ROBO Global Robotics & Automation",
        "BOTZ": "Global X Robotics & Artificial Intelligence",
        # ─── Crypto-Linked ETFs ───
        "IBIT": "iShares Bitcoin Trust",
        "FBTC": "Fidelity Wise Origin Bitcoin",
        "BITO": "ProShares Bitcoin Strategy (futures)",
        "ETHA": "iShares Ethereum Trust",
        "FETH": "Fidelity Ethereum",
        # ─── Income / Covered Call ───
        "JEPI": "JPMorgan Equity Premium Income",
        "JEPQ": "JPMorgan Nasdaq Equity Premium Income",
        "QYLD": "Global X Nasdaq-100 Covered Call",
        "XYLD": "Global X S&P 500 Covered Call",
        "DIVO": "Amplify CWP Enhanced Dividend Income",
        # ─── Alternatives / Trend ───
        "DBMF": "iMGP DBi Managed Futures",
        "KMLM": "KFA Mount Lucas Managed Futures",
        "CTA": "Simplify Managed Futures Strategy",
        "RSST": "Return Stacked US Stocks & Managed Futures",
        # ─── Canadian-Listed (TSX, .TO suffix) ───
        "XIC.TO": "iShares Core S&P/TSX Capped Composite",
        "XIU.TO": "iShares S&P/TSX 60",
        "VCN.TO": "Vanguard FTSE Canada All Cap",
        "ZCN.TO": "BMO S&P/TSX Capped Composite",
        "VFV.TO": "Vanguard S&P 500 (CAD, unhedged)",
        "VSP.TO": "Vanguard S&P 500 (CAD-hedged)",
        "VUN.TO": "Vanguard US Total Market (unhedged)",
        "VXC.TO": "Vanguard FTSE Global All Cap ex-Canada",
        "XEF.TO": "iShares Core MSCI EAFE IMI",
        "VIU.TO": "Vanguard FTSE Developed ex-NA",
        "XEC.TO": "iShares Core MSCI Emerging Markets IMI",
        "VEE.TO": "Vanguard FTSE Emerging Markets",
        "VEQT.TO": "Vanguard All-Equity ETF Portfolio",
        "VGRO.TO": "Vanguard Growth (80/20)",
        "VBAL.TO": "Vanguard Balanced (60/40)",
        "VCNS.TO": "Vanguard Conservative (40/60)",
        "VCIP.TO": "Vanguard Conservative Income (20/80)",
        "VRIF.TO": "Vanguard Retirement Income",
        "XBAL.TO": "iShares Core Balanced (60/40)",
        "XGRO.TO": "iShares Core Growth (80/20)",
        "XCNS.TO": "iShares Core Conservative (40/60)",
        "ZBAL.TO": "BMO Balanced",
        "ZGRO.TO": "BMO Growth",
        "VAB.TO": "Vanguard Canadian Aggregate Bond",
        "ZAG.TO": "BMO Aggregate Bond",
        "XBB.TO": "iShares Core Canadian Universe Bond",
        "CASH.TO": "Horizons High Interest Savings",
        "PSA.TO": "Purpose High Interest Savings",
        "CMR.TO": "iShares Premium Money Market",
        "CSAV.TO": "CI High Interest Savings",
        "XRE.TO": "iShares S&P/TSX Capped REIT",
        "ZDV.TO": "BMO Canadian Dividend",
        "XDIV.TO": "iShares Core MSCI Canadian Quality Dividend",
        "XEG.TO": "iShares S&P/TSX Capped Energy",
        "XFN.TO": "iShares S&P/TSX Capped Financials",
        "HXS.TO": "Global X S&P 500 (corporate class)",
        "HXT.TO": "Global X S&P/TSX 60 (corporate class)",
    },
}

CATEGORIES = list(UNIVERSE.keys())
OTHER = "Other…"


def tickers(category: str) -> list[str]:
    return sorted(UNIVERSE[category].keys())


def label(category: str, symbol: str) -> str:
    if symbol == OTHER:
        return OTHER
    name = UNIVERSE[category].get(symbol, "")
    return f"{symbol} — {name}" if name else symbol
